### ISSUE TITLE
How to fix the down of server: https://danctnix.arikawa-hi.me/rootfs/archarm-on-mobile?

### ISSUE THREAD

**Issue by ghost** [dreemurrs-embedded/archarm-mobile-fde-installer#24] opened 2023-07-18 13:25 UTC
Hello I really would like to reinstall arch with FDE, but I need a workaround for the service https://danctnix.arikawa-hi.me/rootfs/archarm-on-mobile that is down for a few months.

**Comment by Danct12** [comment] 2023-07-18 17:08
Duplicate of #23

**Closed as completed by Danct12** 2023-07-18 17:08 UTC
Labels: duplicate

**Comment by ghost** [comment] 2023-07-20 05:37
Is there a work-around for this problem?
