### ISSUE TITLE
no boot with "Could not parse config file: /etc/osk.conf" after pacman update

### ISSUE THREAD

**Issue by zoharsnir** [dreemurrs-embedded/archarm-mobile-fde-installer#16] opened 2022-06-02 12:42 UTC
Installed on pinephone pro explorer with fork from https://github.com/TECH-SAVIOURS-ORG/archarm-mobile-fde-installer on microsd with no issues.

It was working flawlessly (regarding fde, boot) for some time.

After running pacman -Syu about 2 days ago it stopped booting.

After aqua led comes blue led and then arch / penguin logo with spinning wheel.

When connecting usb keyboard I'm seeing an endless loop of below errors:

 ```
ERROR: Could not parse config file: /etc/osk.conf
ERROR: No valid config file specified, use -c [path
ERROR: Syntax error on line 4
ERROR: Could not parse config file: /etc/osk.conf
ERROR: No valid config file specified, use -c [path]
ERROR: Syntax error on line 4
ERROR: Could not parse config file: /etc/osk.conf
ERROR: No valid config file specified, use -c [path]
```

I'm still able to boot my normal (no fde) arch from emmc.

(Please forgive typos, on mobile)

**Comment by zoharsnir** [comment] 2022-06-04 06:08
https://github.com/dreemurrs-embedded/Pine64-Arch/issues/407#issue-1260642768

**Comment by Danct12** [comment] 2022-06-04 06:09
Duplicate of https://github.com/dreemurrs-embedded/Pine64-Arch/issues/407

**Closed as completed by Danct12** 2022-06-04 06:09 UTC
